language: r
sudo: required
warnings_are_errors: true
r_github_packages:
- jimhester/covr
cache: packages
dd:
- openssl aes-256-cbc -K $encrypted_d5a8c2c3d7b0_key -iv $encrypted_d5a8c2c3d7b0_iv
  -in tests/testthat/token_file.rds.enc -out tests/testthat/token_file.rds -d
after_success:
- Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: change
    on_failure: always
